# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            ABM
tagline:          'A Jekyll theme'
description:      'Join me in learning to Reverse Engineer better.'
url:              https://ablindman10.github.io/
baseurl:          /

author:
  name:           'abm'
  url:            https://ablindman10.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
